import { AppError,bucket,context,db,errorResponse,secureWrite } from '@/lib/classroom-server';
export const dynamic='force-dynamic';
export async function POST(request:Request){try{
 secureWrite(request);const c=await context();if(!['teacher','student'].includes(c.role))throw new AppError('Activa el aula primero.',403);if(Number(request.headers.get('content-length')||0)>11*1024*1024)throw new AppError('Cada archivo puede pesar hasta 10 MB.');const form=await request.formData();const file=form.get('file');const taskId=String(form.get('task')||'');if(!(file instanceof File)||!file.size||file.size>10*1024*1024)throw new AppError('Selecciona un archivo de hasta 10 MB.');
 const task=await db().prepare('SELECT * FROM tasks WHERE id=?').bind(taskId).first<any>();if(!task||(c.role==='student'&&!task.published))throw new AppError('Tarea no encontrada.',404);const sub=await db().prepare('SELECT state FROM submissions WHERE task=?').bind(taskId).first<any>();if(sub&&sub.state!=='draft')throw new AppError('La tarea ya fue entregada. Debe reabrirse para cambiar los archivos.',409);const count=await db().prepare('SELECT COUNT(*) AS n FROM files WHERE task=? AND owner=?').bind(taskId,c.user.userId).first<any>();if(count.n>=10)throw new AppError('Puedes adjuntar hasta 10 archivos por tarea.');
 const data=await file.arrayBuffer();const b=new Uint8Array(data);let mime='';if(b[0]===37&&b[1]===80&&b[2]===68&&b[3]===70&&b[4]===45)mime='application/pdf';if(b[0]===255&&b[1]===216&&b[2]===255)mime='image/jpeg';if(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71&&b[4]===13&&b[5]===10&&b[6]===26&&b[7]===10)mime='image/png';if(new TextDecoder().decode(b.slice(0,4))==='RIFF'&&new TextDecoder().decode(b.slice(8,12))==='WEBP')mime='image/webp';if(!mime)throw new AppError('Usa un PDF o una imagen JPG, PNG o WEBP.');
 const id=crypto.randomUUID();await bucket().put(id,data,{httpMetadata:{contentType:mime}});try{await db().prepare('INSERT INTO files (id,task,owner,kind,name,mime,size) VALUES (?,?,?,?,?,?,?)').bind(id,taskId,c.user.userId,c.role==='teacher'?'material':'solution',file.name.slice(0,180),mime,file.size).run();}catch(e){await bucket().delete(id);throw e;}return Response.json({ok:true,id});
}catch(e){return errorResponse(e);}}
export async function GET(request:Request){try{
 const c=await context();const id=new URL(request.url).searchParams.get('id');const f=await db().prepare('SELECT f.*,t.published FROM files f JOIN tasks t ON t.id=f.task WHERE f.id=?').bind(id).first<any>();if(!f||(c.role!=='teacher'&&!(c.role==='student'&&f.published&&(f.kind==='material'||f.owner===c.user.userId))))throw new AppError('Archivo no encontrado.',404);const data=await bucket().get(f.id);if(!data)throw new AppError('Archivo no disponible.',404);return new Response(data.body,{headers:{'Content-Type':f.mime,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
}catch(e){return errorResponse(e);}}
export async function DELETE(request:Request){try{
 secureWrite(request);const c=await context();const id=new URL(request.url).searchParams.get('id');const f=await db().prepare('SELECT * FROM files WHERE id=? AND owner=?').bind(id,c.user.userId).first<any>();if(!f)throw new AppError('Archivo no encontrado.',404);const s=await db().prepare('SELECT state FROM submissions WHERE task=?').bind(f.task).first<any>();if(s&&s.state!=='draft')throw new AppError('La tarea ya fue entregada.',409);await db().prepare('DELETE FROM files WHERE id=?').bind(f.id).run();await bucket().delete(f.id);return Response.json({ok:true});
}catch(e){return errorResponse(e);}}
