// Generated by scripts/build-progress-service.mjs; do not edit manually.
const SYNC_CATALOGS={
  "fernando": {
    "answer:algebra-uni-c1-basico:alg-uni-c1-b01": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b02": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b02",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b01"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b03": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b03",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b02"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b04": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b04",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b03"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b05": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b05",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b04"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b06": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b06",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b05"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b07": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b07",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b06"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b08": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b08",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b07"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b09": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b09",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b08"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b10": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b10",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b09"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i01": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i02": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i02",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i01"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i03": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i03",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i02"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i04": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i04",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i03"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i05": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i05",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i04"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i06": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i06",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i05"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i07": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i07",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i06"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i08": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i08",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i07"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i09": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i09",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i08"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i10": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i10",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i09"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a01": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a02": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a02",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a01"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a03": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a03",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a02"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a04": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a04",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a03"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a05": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a05",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a04"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a06": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a06",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a05"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a07": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a07",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a06"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a08": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a08",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a07"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a09": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a09",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a08"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a10": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a10",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a09"
    },
    "topic:uni-c1-mapa": {
      "kind": "topic",
      "topicId": "uni-c1-mapa"
    },
    "topic:uni-c1-naturales": {
      "kind": "topic",
      "topicId": "uni-c1-naturales"
    },
    "topic:uni-c1-enteros": {
      "kind": "topic",
      "topicId": "uni-c1-enteros"
    },
    "topic:uni-c1-racionales": {
      "kind": "topic",
      "topicId": "uni-c1-racionales"
    },
    "topic:uni-c1-decimales": {
      "kind": "topic",
      "topicId": "uni-c1-decimales"
    },
    "topic:uni-c1-reales": {
      "kind": "topic",
      "topicId": "uni-c1-reales"
    },
    "topic:uni-c1-complejos": {
      "kind": "topic",
      "topicId": "uni-c1-complejos"
    },
    "topic:uni-c1-operaciones": {
      "kind": "topic",
      "topicId": "uni-c1-operaciones"
    },
    "topic:uni-c1-sumas": {
      "kind": "topic",
      "topicId": "uni-c1-sumas"
    },
    "topic:uni-c1-despeje": {
      "kind": "topic",
      "topicId": "uni-c1-despeje"
    }
  },
  "josue": {
    "answer:josue-p4-u1-basico:josue-p4-u1-b01": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b01",
      "choices": 5,
      "previous": null
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b02": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b02",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b01"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b03": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b03",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b02"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b04": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b04",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b03"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b05": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b05",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b04"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b06": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b06",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b05"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b07": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b07",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b06"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b08": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b08",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b07"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b09": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b09",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b08"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b10": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b10",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b09"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i01": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i01",
      "choices": 5,
      "previous": null
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i02": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i02",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i01"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i03": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i03",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i02"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i04": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i04",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i03"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i05": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i05",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i04"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i06": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i06",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i05"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i07": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i07",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i06"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i08": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i08",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i07"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i09": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i09",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i08"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i10": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i10",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i09"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a01": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a01",
      "choices": 5,
      "previous": null
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a02": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a02",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a01"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a03": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a03",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a02"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a04": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a04",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a03"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a05": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a05",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a04"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a06": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a06",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a05"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a07": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a07",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a06"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a08": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a08",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a07"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a09": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a09",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a08"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a10": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a10",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a09"
    },
    "topic:josue-p4-u1-t01": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t01"
    },
    "topic:josue-p4-u1-t02": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t02"
    },
    "topic:josue-p4-u1-t03": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t03"
    },
    "topic:josue-p4-u1-t04": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t04"
    },
    "topic:josue-p4-u1-t05": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t05"
    },
    "topic:josue-p4-u1-t06": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t06"
    },
    "topic:josue-p4-u1-t07": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t07"
    },
    "topic:josue-p4-u1-t08": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t08"
    },
    "topic:josue-p4-u1-t09": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t09"
    },
    "topic:josue-p4-u1-t10": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t10"
    }
  }
};

// Shared, bounded data protocol. Also bundled for Google Apps Script.
const SYNC_VERSION=1;
const owns=(object,key)=>Object.prototype.hasOwnProperty.call(object,key);
function progressCatalog(course) {
  const catalog={};
  for(const task of course.tasks.filter(task=>task.published)){
    task.questions.forEach((question,index)=>{
      catalog[`answer:${task.id}:${question.id}`]={kind:'answer',taskId:task.id,questionId:question.id,choices:question.options.length,
        previous:index?`answer:${task.id}:${task.questions[index-1].id}`:null};
    });
  }
  for(const topic of course.lesson.topics)catalog[`topic:${topic.id}`]={kind:'topic',topicId:topic.id};
  return catalog;
}
function emptyProgress(studentId) {
  if(!['fernando','josue'].includes(studentId))throw new Error('Alumno no válido.');
  return {version:SYNC_VERSION,studentId,revision:0,fields:{}};
}
function validValue(spec,value) {
  return spec?.kind==='topic'?typeof value==='boolean':spec?.kind==='answer'&&Number.isInteger(value)&&value>=0&&value<spec.choices;
}
function validateRemote(input,studentId,catalog) {
  if(input?.version!==SYNC_VERSION||input.studentId!==studentId||!Number.isSafeInteger(input.revision)||input.revision<0||!input.fields||Array.isArray(input.fields))throw new Error('El servicio devolvió un avance no válido.');
  const fields={};
  for(const [key,field] of Object.entries(input.fields)){
    if(!owns(catalog,key)||!validValue(catalog[key],field?.value)||!Number.isSafeInteger(field.revision)||field.revision<1||field.revision>input.revision||typeof field.opId!=='string'||!/^[-a-zA-Z0-9]{8,80}$/.test(field.opId)||typeof field.updatedAt!=='string'||!Number.isFinite(Date.parse(field.updatedAt)))throw new Error('El servicio devolvió una respuesta no válida.');
    fields[key]={value:field.value,revision:field.revision,opId:field.opId,updatedAt:field.updatedAt};
  }
  return {version:SYNC_VERSION,studentId,revision:input.revision,fields};
}
function validateOperations(operations,catalog) {
  if(!Array.isArray(operations)||operations.length>100)throw new Error('Demasiados cambios en una petición.');
  const fields=new Set(),ids=new Set();
  return operations.map(op=>{
    if(!op||!owns(catalog,op.field)||!validValue(catalog[op.field],op.value)||typeof op.id!=='string'||!/^[-a-zA-Z0-9]{8,80}$/.test(op.id)||ids.has(op.id)||fields.has(op.field)||!Number.isSafeInteger(op.baseRevision)||op.baseRevision<0||typeof op.seed!=='boolean')throw new Error('Cambio de avance no válido.');
    const supersedes=op.supersedes||[];
    if(!Array.isArray(supersedes)||supersedes.length>20||supersedes.some(id=>typeof id!=='string'||!/^[-a-zA-Z0-9]{8,80}$/.test(id)))throw new Error('Historial de cambio no válido.');
    fields.add(op.field);ids.add(op.id);
    return {id:op.id,field:op.field,value:op.value,baseRevision:op.baseRevision,seed:op.seed,supersedes};
  });
}
function mergeProgress(current,operations,catalog,now) {
  const next=validateRemote(current,current.studentId,catalog),accepted=[],conflicts=[];
  const order=Object.keys(catalog);
  const changes=validateOperations(operations,catalog).sort((a,b)=>order.indexOf(a.field)-order.indexOf(b.field));
  for(const op of changes){
    const before=next.fields[op.field],spec=catalog[op.field];
    // Old devices only fill missing fields. They never overwrite shared answers.
    if((op.seed&&before)||before?.value===op.value){accepted.push(op.id);continue;}
    if(((before?.revision||0)!==op.baseRevision&&!op.supersedes.includes(before?.opId))||(!op.seed&&spec.previous&&!next.fields[spec.previous])){
      conflicts.push({id:op.id,field:op.field});continue;
    }
    next.revision++;
    next.fields[op.field]={value:op.value,revision:next.revision,opId:op.id,updatedAt:now};
    accepted.push(op.id);
  }
  return {ok:true,state:next,accepted,conflicts};
}
