// INSTALACIÓN: copia todo este archivo en Code.gs de Apps Script.
// ACTUALIZACIÓN: usa el MISMO proyecto y la MISMA implementación para conservar el avance.
// Esta versión reúne el catálogo y el servicio en un único archivo.
// Guarda solo respuestas y temas repasados. Lee los capítulos publicados en GitHub.
// No accede a Drive ni al correo. Requiere permiso de conexión a servicios externos.

// Generated by scripts/build-progress-service.mjs; do not edit manually.
const SYNC_CATALOGS={
  "fernando": {
    "answer:algebra-uni-c1-basico:alg-uni-c1-b01": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b02": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b02",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b01"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b03": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b03",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b02"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b04": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b04",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b03"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b05": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b05",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b04"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b06": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b06",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b05"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b07": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b07",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b06"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b08": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b08",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b07"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b09": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b09",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b08"
    },
    "answer:algebra-uni-c1-basico:alg-uni-c1-b10": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-basico",
      "questionId": "alg-uni-c1-b10",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-basico:alg-uni-c1-b09"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i01": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i02": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i02",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i01"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i03": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i03",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i02"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i04": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i04",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i03"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i05": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i05",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i04"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i06": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i06",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i05"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i07": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i07",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i06"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i08": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i08",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i07"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i09": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i09",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i08"
    },
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i10": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-intermedio",
      "questionId": "alg-uni-c1-i10",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-intermedio:alg-uni-c1-i09"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a01": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a02": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a02",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a01"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a03": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a03",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a02"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a04": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a04",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a03"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a05": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a05",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a04"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a06": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a06",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a05"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a07": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a07",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a06"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a08": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a08",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a07"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a09": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a09",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a08"
    },
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a10": {
      "kind": "answer",
      "taskId": "algebra-uni-c1-avanzado",
      "questionId": "alg-uni-c1-a10",
      "choices": 5,
      "previous": "answer:algebra-uni-c1-avanzado:alg-uni-c1-a09"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b01": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b02": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b02",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b01"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b03": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b03",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b02"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b04": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b04",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b03"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b05": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b05",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b04"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b06": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b06",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b05"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b07": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b07",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b06"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b08": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b08",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b07"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b09": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b09",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b08"
    },
    "answer:algebra-uni-c2-basico:alg-uni-c2-b10": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-basico",
      "questionId": "alg-uni-c2-b10",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-basico:alg-uni-c2-b09"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i01": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i02": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i02",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i01"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i03": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i03",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i02"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i04": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i04",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i03"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i05": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i05",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i04"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i06": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i06",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i05"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i07": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i07",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i06"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i08": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i08",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i07"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i09": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i09",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i08"
    },
    "answer:algebra-uni-c2-intermedio:alg-uni-c2-i10": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-intermedio",
      "questionId": "alg-uni-c2-i10",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-intermedio:alg-uni-c2-i09"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a01": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a01",
      "choices": 5,
      "previous": null
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a02": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a02",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a01"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a03": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a03",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a02"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a04": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a04",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a03"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a05": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a05",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a04"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a06": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a06",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a05"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a07": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a07",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a06"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a08": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a08",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a07"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a09": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a09",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a08"
    },
    "answer:algebra-uni-c2-avanzado:alg-uni-c2-a10": {
      "kind": "answer",
      "taskId": "algebra-uni-c2-avanzado",
      "questionId": "alg-uni-c2-a10",
      "choices": 5,
      "previous": "answer:algebra-uni-c2-avanzado:alg-uni-c2-a09"
    },
    "topic:uni-c1-mapa": {
      "kind": "topic",
      "topicId": "uni-c1-mapa"
    },
    "topic:uni-c1-naturales": {
      "kind": "topic",
      "topicId": "uni-c1-naturales"
    },
    "topic:uni-c1-enteros": {
      "kind": "topic",
      "topicId": "uni-c1-enteros"
    },
    "topic:uni-c1-racionales": {
      "kind": "topic",
      "topicId": "uni-c1-racionales"
    },
    "topic:uni-c1-decimales": {
      "kind": "topic",
      "topicId": "uni-c1-decimales"
    },
    "topic:uni-c1-reales": {
      "kind": "topic",
      "topicId": "uni-c1-reales"
    },
    "topic:uni-c1-complejos": {
      "kind": "topic",
      "topicId": "uni-c1-complejos"
    },
    "topic:uni-c1-operaciones": {
      "kind": "topic",
      "topicId": "uni-c1-operaciones"
    },
    "topic:uni-c1-sumas": {
      "kind": "topic",
      "topicId": "uni-c1-sumas"
    },
    "topic:uni-c1-despeje": {
      "kind": "topic",
      "topicId": "uni-c1-despeje"
    },
    "topic:uni-c2-potencias": {
      "kind": "topic",
      "topicId": "uni-c2-potencias"
    },
    "topic:uni-c2-negativos": {
      "kind": "topic",
      "topicId": "uni-c2-negativos"
    },
    "topic:uni-c2-leyes": {
      "kind": "topic",
      "topicId": "uni-c2-leyes"
    },
    "topic:uni-c2-torres": {
      "kind": "topic",
      "topicId": "uni-c2-torres"
    },
    "topic:uni-c2-raices": {
      "kind": "topic",
      "topicId": "uni-c2-raices"
    },
    "topic:uni-c2-radicales": {
      "kind": "topic",
      "topicId": "uni-c2-radicales"
    },
    "topic:uni-c2-fraccionarios": {
      "kind": "topic",
      "topicId": "uni-c2-fraccionarios"
    },
    "topic:uni-c2-anidados": {
      "kind": "topic",
      "topicId": "uni-c2-anidados"
    },
    "topic:uni-c2-ecuaciones": {
      "kind": "topic",
      "topicId": "uni-c2-ecuaciones"
    },
    "topic:uni-c2-estrategias": {
      "kind": "topic",
      "topicId": "uni-c2-estrategias"
    }
  },
  "josue": {
    "answer:josue-p4-u1-basico:josue-p4-u1-b01": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b01",
      "choices": 5,
      "previous": null
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b02": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b02",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b01"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b03": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b03",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b02"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b04": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b04",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b03"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b05": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b05",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b04"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b06": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b06",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b05"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b07": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b07",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b06"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b08": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b08",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b07"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b09": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b09",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b08"
    },
    "answer:josue-p4-u1-basico:josue-p4-u1-b10": {
      "kind": "answer",
      "taskId": "josue-p4-u1-basico",
      "questionId": "josue-p4-u1-b10",
      "choices": 5,
      "previous": "answer:josue-p4-u1-basico:josue-p4-u1-b09"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i01": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i01",
      "choices": 5,
      "previous": null
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i02": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i02",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i01"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i03": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i03",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i02"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i04": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i04",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i03"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i05": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i05",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i04"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i06": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i06",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i05"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i07": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i07",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i06"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i08": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i08",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i07"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i09": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i09",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i08"
    },
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i10": {
      "kind": "answer",
      "taskId": "josue-p4-u1-intermedio",
      "questionId": "josue-p4-u1-i10",
      "choices": 5,
      "previous": "answer:josue-p4-u1-intermedio:josue-p4-u1-i09"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a01": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a01",
      "choices": 5,
      "previous": null
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a02": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a02",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a01"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a03": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a03",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a02"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a04": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a04",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a03"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a05": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a05",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a04"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a06": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a06",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a05"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a07": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a07",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a06"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a08": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a08",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a07"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a09": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a09",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a08"
    },
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a10": {
      "kind": "answer",
      "taskId": "josue-p4-u1-avanzado",
      "questionId": "josue-p4-u1-a10",
      "choices": 5,
      "previous": "answer:josue-p4-u1-avanzado:josue-p4-u1-a09"
    },
    "topic:josue-p4-u1-t01": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t01"
    },
    "topic:josue-p4-u1-t02": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t02"
    },
    "topic:josue-p4-u1-t03": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t03"
    },
    "topic:josue-p4-u1-t04": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t04"
    },
    "topic:josue-p4-u1-t05": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t05"
    },
    "topic:josue-p4-u1-t06": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t06"
    },
    "topic:josue-p4-u1-t07": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t07"
    },
    "topic:josue-p4-u1-t08": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t08"
    },
    "topic:josue-p4-u1-t09": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t09"
    },
    "topic:josue-p4-u1-t10": {
      "kind": "topic",
      "topicId": "josue-p4-u1-t10"
    }
  }
};

const SYNC_LEGACY_FIELDS={
  "fernando": [
    "answer:algebra-uni-c1-basico:alg-uni-c1-b01",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b02",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b03",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b04",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b05",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b06",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b07",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b08",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b09",
    "answer:algebra-uni-c1-basico:alg-uni-c1-b10",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i01",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i02",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i03",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i04",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i05",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i06",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i07",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i08",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i09",
    "answer:algebra-uni-c1-intermedio:alg-uni-c1-i10",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a01",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a02",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a03",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a04",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a05",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a06",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a07",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a08",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a09",
    "answer:algebra-uni-c1-avanzado:alg-uni-c1-a10",
    "topic:uni-c1-mapa",
    "topic:uni-c1-naturales",
    "topic:uni-c1-enteros",
    "topic:uni-c1-racionales",
    "topic:uni-c1-decimales",
    "topic:uni-c1-reales",
    "topic:uni-c1-complejos",
    "topic:uni-c1-operaciones",
    "topic:uni-c1-sumas",
    "topic:uni-c1-despeje"
  ],
  "josue": [
    "answer:josue-p4-u1-basico:josue-p4-u1-b01",
    "answer:josue-p4-u1-basico:josue-p4-u1-b02",
    "answer:josue-p4-u1-basico:josue-p4-u1-b03",
    "answer:josue-p4-u1-basico:josue-p4-u1-b04",
    "answer:josue-p4-u1-basico:josue-p4-u1-b05",
    "answer:josue-p4-u1-basico:josue-p4-u1-b06",
    "answer:josue-p4-u1-basico:josue-p4-u1-b07",
    "answer:josue-p4-u1-basico:josue-p4-u1-b08",
    "answer:josue-p4-u1-basico:josue-p4-u1-b09",
    "answer:josue-p4-u1-basico:josue-p4-u1-b10",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i01",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i02",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i03",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i04",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i05",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i06",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i07",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i08",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i09",
    "answer:josue-p4-u1-intermedio:josue-p4-u1-i10",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a01",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a02",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a03",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a04",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a05",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a06",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a07",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a08",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a09",
    "answer:josue-p4-u1-avanzado:josue-p4-u1-a10",
    "topic:josue-p4-u1-t01",
    "topic:josue-p4-u1-t02",
    "topic:josue-p4-u1-t03",
    "topic:josue-p4-u1-t04",
    "topic:josue-p4-u1-t05",
    "topic:josue-p4-u1-t06",
    "topic:josue-p4-u1-t07",
    "topic:josue-p4-u1-t08",
    "topic:josue-p4-u1-t09",
    "topic:josue-p4-u1-t10"
  ]
};

// Shared, bounded data protocol. Also bundled for Google Apps Script.
const SYNC_VERSION=1;
const owns=(object,key)=>Object.prototype.hasOwnProperty.call(object,key);
function progressCatalog(course) {
  const catalog={};
  for(const task of course.tasks.filter(task=>task.published)){
    task.questions.forEach((question,index)=>{
      catalog[`answer:${task.id}:${question.id}`]={kind:'answer',taskId:task.id,questionId:question.id,choices:question.options.length,
        previous:index?`answer:${task.id}:${task.questions[index-1].id}`:null};
    });
  }
  for(const lesson of [course.lesson,...(course.additionalLessons||[])])for(const topic of lesson.topics)catalog[`topic:${topic.id}`]={kind:'topic',topicId:topic.id};
  return catalog;
}
function emptyProgress(studentId) {
  if(!['fernando','josue'].includes(studentId))throw new Error('Alumno no válido.');
  return {version:SYNC_VERSION,studentId,revision:0,fields:{}};
}
function validValue(spec,value) {
  return spec?.kind==='topic'?typeof value==='boolean':spec?.kind==='answer'&&Number.isInteger(value)&&value>=0&&value<spec.choices;
}
function validateRemote(input,studentId,catalog) {
  if(input?.version!==SYNC_VERSION||input.studentId!==studentId||!Number.isSafeInteger(input.revision)||input.revision<0||!input.fields||Array.isArray(input.fields))throw new Error('El servicio devolvió un avance no válido.');
  const fields={};
  for(const [key,field] of Object.entries(input.fields)){
    if(!owns(catalog,key)||!validValue(catalog[key],field?.value)||!Number.isSafeInteger(field.revision)||field.revision<1||field.revision>input.revision||typeof field.opId!=='string'||!/^[-a-zA-Z0-9]{8,80}$/.test(field.opId)||typeof field.updatedAt!=='string'||!Number.isFinite(Date.parse(field.updatedAt)))throw new Error('El servicio devolvió una respuesta no válida.');
    fields[key]={value:field.value,revision:field.revision,opId:field.opId,updatedAt:field.updatedAt};
  }
  return {version:SYNC_VERSION,studentId,revision:input.revision,fields};
}
function validateOperations(operations,catalog) {
  if(!Array.isArray(operations)||operations.length>100)throw new Error('Demasiados cambios en una petición.');
  const fields=new Set(),ids=new Set();
  return operations.map(op=>{
    if(!op||!owns(catalog,op.field)||!validValue(catalog[op.field],op.value)||typeof op.id!=='string'||!/^[-a-zA-Z0-9]{8,80}$/.test(op.id)||ids.has(op.id)||fields.has(op.field)||!Number.isSafeInteger(op.baseRevision)||op.baseRevision<0||typeof op.seed!=='boolean')throw new Error('Cambio de avance no válido.');
    const supersedes=op.supersedes||[];
    if(!Array.isArray(supersedes)||supersedes.length>20||supersedes.some(id=>typeof id!=='string'||!/^[-a-zA-Z0-9]{8,80}$/.test(id)))throw new Error('Historial de cambio no válido.');
    fields.add(op.field);ids.add(op.id);
    return {id:op.id,field:op.field,value:op.value,baseRevision:op.baseRevision,seed:op.seed,supersedes};
  });
}
function mergeProgress(current,operations,catalog,now) {
  const next=validateRemote(current,current.studentId,catalog),accepted=[],conflicts=[];
  const order=Object.keys(catalog);
  const changes=validateOperations(operations,catalog).sort((a,b)=>order.indexOf(a.field)-order.indexOf(b.field));
  for(const op of changes){
    const before=next.fields[op.field],spec=catalog[op.field];
    // Old devices only fill missing fields. They never overwrite shared answers.
    if((op.seed&&before)||before?.value===op.value){accepted.push(op.id);continue;}
    if(((before?.revision||0)!==op.baseRevision&&!op.supersedes.includes(before?.opId))||(!op.seed&&spec.previous&&!next.fields[spec.previous])){
      conflicts.push({id:op.id,field:op.field});continue;
    }
    next.revision++;
    next.fields[op.field]={value:op.value,revision:next.revision,opId:op.id,updatedAt:now};
    accepted.push(op.id);
  }
  return {ok:true,state:next,accepted,conflicts};
}

/** Read only the owner's published course. Clients never define valid questions. */
const PROGRESS_COURSE_URLS={
  fernando:'https://raw.githubusercontent.com/aludenah/fernando/main/docs/data/course.json',
  josue:'https://raw.githubusercontent.com/aludenah/fernando/main/docs/data/josue-course.json'
};
function progressCourseCatalog_(course) {
  var identifier=function(value){return typeof value==='string'&&/^[-a-zA-Z0-9_]{1,100}$/.test(value);};
  if(!course||course.schemaVersion!==2||!course.lesson||!Array.isArray(course.tasks)||course.tasks.length>500||
    (course.additionalLessons!==undefined&&!Array.isArray(course.additionalLessons)))throw new Error('Curso no válido.');
  var lessons=[course.lesson].concat(course.additionalLessons||[]),lessonIds=new Set(),taskIds=new Set(),topicIds=new Set();
  if(lessons.length>100)throw new Error('Demasiados capítulos.');
  for(var lesson of lessons){
    if(!identifier(lesson.id)||lessonIds.has(lesson.id)||!Array.isArray(lesson.topics)||lesson.topics.length>100)throw new Error('Capítulo no válido.');
    lessonIds.add(lesson.id);
    for(var topic of lesson.topics){
      if(!identifier(topic.id)||topicIds.has(topic.id))throw new Error('Tema no válido.');
      topicIds.add(topic.id);
    }
  }
  for(var task of course.tasks){
    if(!task.published)continue;
    if(!identifier(task.id)||taskIds.has(task.id)||!lessonIds.has(task.chapterId)||!Array.isArray(task.questions)||!task.questions.length||task.questions.length>100)throw new Error('Tarea no válida.');
    taskIds.add(task.id);
    var questionIds=new Set();
    for(var question of task.questions){
      if(!identifier(question.id)||questionIds.has(question.id)||!Array.isArray(question.options)||question.options.length<2||question.options.length>10)throw new Error('Pregunta no válida.');
      questionIds.add(question.id);
    }
  }
  var catalog=progressCatalog(course);
  if(!Object.keys(catalog).length||Object.keys(catalog).length>5000)throw new Error('Catálogo demasiado grande.');
  return catalog;
}
function progressPackCatalog_(catalog) {
  var tasks=new Map(),topics=[];
  for(var field of Object.keys(catalog)){
    var spec=catalog[field];
    if(spec.kind==='topic'){topics.push(spec.topicId);continue;}
    if(!tasks.has(spec.taskId))tasks.set(spec.taskId,[]);
    tasks.get(spec.taskId).push([spec.questionId,spec.choices,spec.previous?spec.previous.split(':')[2]:null]);
  }
  return {tasks:Array.from(tasks.entries()),topics:topics};
}
function progressUnpackCatalog_(packed) {
  var catalog={},identifier=function(value){return typeof value==='string'&&/^[-a-zA-Z0-9_]{1,100}$/.test(value);};
  for(var task of packed.tasks){
    if(!identifier(task[0]))throw new Error('Caché no válida.');
    for(var q of task[1]){
      if(!identifier(q[0])||!Number.isInteger(q[1])||q[1]<2||q[1]>10||(q[2]!==null&&!identifier(q[2])))throw new Error('Caché no válida.');
      catalog['answer:'+task[0]+':'+q[0]]={kind:'answer',taskId:task[0],questionId:q[0],choices:q[1],previous:q[2]===null?null:'answer:'+task[0]+':'+q[2]};
    }
  }
  for(var topic of packed.topics){
    if(!identifier(topic))throw new Error('Caché no válida.');
    catalog['topic:'+topic]={kind:'topic',topicId:topic};
  }
  if(!Object.keys(catalog).length||Object.keys(catalog).length>5000)throw new Error('Caché no válida.');
  return catalog;
}
function progressPublishedCatalog_(studentId,known) {
  var fallback=SYNC_CATALOGS[studentId],cache=null,cached=null,key='published-catalog-v1:'+studentId;
  try{
    cache=CacheService.getScriptCache();
    var text=cache.get(key);
    if(text){
      cached=JSON.parse(text);
      if(!cached||!Number.isFinite(cached.fetchedAt))cached=null;
      else cached.catalog=progressUnpackCatalog_(cached.packed);
    }
  }catch(error){cached=null;}
  var now=Date.now(),age=cached?now-cached.fetchedAt:Infinity;
  // A new chapter can refresh a cached catalogue early; ordinary reads reuse it.
  var missing=cached&&known&&known.some(function(field){return !Object.prototype.hasOwnProperty.call(cached.catalog,field);});
  if(cached&&age<60000&&(!missing||age<15000))return {catalog:cached.catalog,unavailable:false,source:'cache'};
  try{
    var response=UrlFetchApp.fetch(PROGRESS_COURSE_URLS[studentId],{method:'get',followRedirects:false,muteHttpExceptions:true});
    if(response.getResponseCode()!==200)throw new Error('No se pudo consultar el curso.');
    var source=response.getContentText();
    if(source.length>4000000)throw new Error('Curso demasiado grande.');
    var catalog=Object.assign({},fallback,progressCourseCatalog_(JSON.parse(source)));
    var serialized=JSON.stringify({fetchedAt:now,packed:progressPackCatalog_(catalog)});
    // CacheService has a 100 KB limit per value. Skipping an oversized cache is safe.
    if(cache&&serialized.length<95000){try{cache.put(key,serialized,21600);}catch(error){}}
    return {catalog:catalog,unavailable:false,source:'published'};
  }catch(error){
    // An outage must not manufacture zero progress or remove any stored answer.
    return {catalog:cached?cached.catalog:fallback,unavailable:true,source:cached?'cache':'bundled'};
  }
}

/** Shared progress only. No Drive files, email, OAuth tokens, or credentials. */
function progressJson_(value) {
  return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);
}
function progressRequest_(input,readAll) {
  if(input.version!==1||!Object.prototype.hasOwnProperty.call(SYNC_CATALOGS,input.studentId))throw new Error('Alumno o versión no válidos.');
  var known=input.knownFields===undefined?SYNC_LEGACY_FIELDS[input.studentId]:input.knownFields;
  if(!Array.isArray(known)||known.length>5000||known.some(function(field){return typeof field!=='string'||field.length>250;}))throw new Error('Catálogo de cliente no válido.');
  var published=progressPublishedCatalog_(input.studentId,readAll?null:known),catalog=published.catalog;
  if(published.unavailable&&known.some(function(field){return !Object.prototype.hasOwnProperty.call(catalog,field);}))throw new Error('No se pudo consultar el capítulo.');
  if(readAll)known=Object.keys(catalog);
  validateOperations(input.operations,catalog); // Reject the entire invalid batch before any write.
  var lock=LockService.getScriptLock();
  lock.waitLock(10000);
  try{
    var properties=PropertiesService.getScriptProperties();
    var prefix='progress-v1:'+input.studentId+':',saved=properties.getProperties();
    var state=emptyProgress(input.studentId);
    for(var key of Object.keys(saved)){
      if(!key.startsWith(prefix))continue;
      var field=key.slice(prefix.length),entry=JSON.parse(saved[key]);
      state.revision=Math.max(state.revision,entry.revision);
      if(Object.prototype.hasOwnProperty.call(catalog,field))state.fields[field]=entry;
      else if(readAll&&published.unavailable)throw new Error('No se pudo consultar todo el avance.');
    }
    var result=mergeProgress(state,input.operations,catalog,new Date().toISOString());
    var changed={};
    for(var key of Object.keys(result.state.fields)){
      var value=JSON.stringify(result.state.fields[key]);
      if(saved[prefix+key]!==value)changed[prefix+key]=value;
    }
    // Each small field stays far below the per-property storage limit.
    if(Object.keys(changed).length)properties.setProperties(changed,false);
    // Older installed pages must not receive fields they cannot validate.
    // Filtering the response never deletes properties belonging to other chapters.
    result.state.fields=Object.fromEntries(Object.entries(result.state.fields).filter(function(entry){return known.indexOf(entry[0])!==-1;}));
    result.supportedFields=Object.keys(catalog);
    result.catalogSource=published.source;
    return result;
  }finally{lock.releaseLock();}
}
function doPost(event) {
  try{
    var body=event&&event.postData&&event.postData.contents;
    if(typeof body!=='string'||body.length>1500000)throw new Error('Petición no válida.');
    return progressJson_(progressRequest_(JSON.parse(body)));
  }catch(error){return progressJson_({ok:false,error:'No se pudo confirmar el avance. Reintenta en unos momentos.'});}
}
function doGet(event) {
  try{
    var studentId=event&&event.parameter&&event.parameter.studentId;
    if(!studentId)return progressJson_({ok:true,service:'aula-progress',version:1});
    return progressJson_(progressRequest_({version:1,studentId:studentId,operations:[]},true));
  }catch(error){return progressJson_({ok:false,error:'No se pudo consultar el avance.'});}
}
