'use client';
import { useCallback,useEffect,useState } from 'react';
import { BookOpen,Plus,ArrowLeft,ArrowUpRight,Check,CheckCircle2,Clock3,FileText,Upload,Download,Trash2,GraduationCap,ChevronRight,Send,Save,Eye,LockKeyhole,LoaderCircle,RefreshCw,ClipboardCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
type Question={id:string;text:string;options:string[];correct?:number};
type Task={id?:string;title:string;subject:string;instructions:string;due:string;questions:Question[];published:boolean;created?:string};
type Submission={task:string;answers:Record<string,number>;state:string;submitted:string|null;score:number|null;feedback:string};
type Attachment={id:string;task:string;kind:string;name:string;mime:string;size:number};
type Data={role:string;email:string;studentEmail?:string;tasks:Task[];submissions:Submission[];files:Attachment[]};
const letters=['A','B','C','D','E'];
const newQuestion=():Question=>({id:crypto.randomUUID(),text:'',options:['','','','',''],correct:0});
const blankTask=():Task=>({title:'',subject:'',instructions:'Resuelve cada pregunta, marca una alternativa y adjunta una foto o un PDF con tu desarrollo.',due:'',questions:[newQuestion()],published:false});
const formatDate=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString('es-PE',{day:'numeric',month:'short',year:'numeric'}):'Sin fecha límite';
const stateLabel=(s?:Submission)=>s?.state==='reviewed'?'Revisada':s?.state==='submitted'?'Por revisar':s?.state==='draft'?'En progreso':'Pendiente';
async function request(url:string,init?:RequestInit):Promise<any>{const r=await fetch(url,init);let j:any;try{j=await r.json();}catch{throw new Error('No hay conexión con el aula. Intenta de nuevo.');}if(!r.ok)throw new Error(j.error||'No se pudo guardar.');return j;}
const post=(b:unknown)=>request('/api/classroom',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
export default function Classroom(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('tasks'),[active,setActive]=useState<string|null>(null),[editor,setEditor]=useState<Task|null>(null),[preview,setPreview]=useState(false),[answers,setAnswers]=useState<Record<string,number>>({}),[dirty,setDirty]=useState(false),[score,setScore]=useState(''),[feedback,setFeedback]=useState(''),[studentEmail,setStudentEmail]=useState('');
 const reload=useCallback(async()=>{const d=await request('/api/classroom');setData(d);setStudentEmail(d.studentEmail||'');return d as Data;},[]);
 useEffect(()=>{reload().catch(e=>setError(e.message));},[reload]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty||editor){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty,editor]);
 async function run(fn:()=>Promise<void>,message=''){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();if(message)setNotice(message);}catch(e){setError(e instanceof Error?e.message:'No se pudo completar la acción.');}finally{setBusy(false);}}
 const isTeacher=data?.role==='teacher'&&!preview;
 const task=data?.tasks.find(t=>t.id===active);
 const sub=data?.submissions.find(s=>s.task===active);
 const locked=!!sub&&sub.state!=='draft';
 const visibleTasks=data?.tasks.filter(t=>!preview||t.published)||[];
 const completed=data?.submissions.filter(s=>s.state==='reviewed').length||0;
 const pendingReview=data?.submissions.filter(s=>s.state==='submitted').length||0;
 const pending=data?.tasks.filter(t=>t.published&&!data.submissions.some(s=>s.task===t.id&&s.state!=='draft')).length||0;
 function openTask(t:Task){setActive(t.id!);setEditor(null);setNotice('');setError('');const s=data?.submissions.find(s=>s.task===t.id);setAnswers(s?.answers||{});setDirty(false);setFeedback(s?.feedback||'');const count=t.questions.filter(q=>q.correct!==undefined&&s?.answers[q.id]===q.correct).length;setScore(String(s?.score??Math.round(count/t.questions.length*20*10)/10));window.scrollTo({top:0,behavior:'smooth'});}
 useEffect(()=>{
  const mc=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>Promise<void>|void}}).modelContext;if(!mc)return;const lifecycle=new AbortController();
  const register=(t:unknown)=>{try{Promise.resolve(mc.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'list_classroom_tasks',title:'Consultar tareas',description:'Lista las tareas visibles del aula y sus estados sin modificarlas.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Se espera un objeto vacío.');return {tasks:visibleTasks.map(t=>({id:t.id,title:t.title,status:stateLabel(data?.submissions.find(s=>s.task===t.id))}))};}});
  register({name:'open_classroom_task',title:'Abrir tarea',description:'Abre una tarea visible para leerla; no marca ni entrega respuestas.',inputSchema:{type:'object',properties:{taskId:{type:'string'}},required:['taskId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input.taskId!=='string'||Object.keys(input).some(k=>k!=='taskId'))throw new Error('Identificador inválido.');if(dirty||editor)throw new Error('Guarda tu trabajo antes de cambiar de tarea.');const t=visibleTasks.find(t=>t.id===input.taskId);if(!t)throw new Error('Tarea no disponible.');openTask(t);await new Promise(r=>setTimeout(r,0));return {opened:t.id};}});
  return()=>lifecycle.abort();
 },[data,preview,dirty,editor]);
 async function back(){await run(async()=>{if(dirty&&task&&data?.role==='student'){await post({action:'answers',task:task.id,answers,submit:false});await reload();setDirty(false);}setActive(null);setEditor(null);});}
 function editQuestion(index:number,update:Partial<Question>){setEditor(e=>e?{...e,questions:e.questions.map((q,i)=>i===index?{...q,...update}:q)}:e);}
 async function saveTask(published:boolean){if(!editor)return;await run(async()=>{const r=await post({action:'saveTask',task:{...editor,published}});const d=await reload();setEditor(null);const saved=d.tasks.find(t=>t.id===r.id)!;setActive(saved.id!);setAnswers({});setDirty(false);},published?'Tarea publicada.':'Borrador guardado. Puedes adjuntar el material antes de publicarlo.');}
 async function upload(files:FileList|null){if(!task||!files)return;const selected=Array.from(files);await run(async()=>{let done=0;try{for(const f of selected){if(f.size>10*1024*1024)throw new Error(`${f.name}: el máximo es 10 MB.`);const form=new FormData();form.set('task',task.id!);form.set('file',f);await request('/api/files',{method:'POST',body:form});done++;}}finally{await reload();}setNotice(`${done} archivo${done===1?'':'s'} guardado${done===1?'':'s'}.`);});}
 function attachments(kind:string,editable=false){const items=data?.files.filter(f=>f.task===active&&f.kind===kind)||[];return <div className="file-list">{items.map(f=><div className="file-row" key={f.id}><FileText size={20}/><a href={`/api/files?id=${encodeURIComponent(f.id)}`} target="_blank" rel="noreferrer"><span>{f.name}</span><small>{(f.size/1024/1024).toFixed(2)} MB</small></a><Download size={17}/>{editable&&!locked&&<Button variant="ghost" size="icon" aria-label={`Quitar ${f.name}`} disabled={busy} onClick={()=>run(async()=>{await request(`/api/files?id=${encodeURIComponent(f.id)}`,{method:'DELETE'});await reload();},'Archivo retirado.')}><Trash2 size={16}/></Button>}</div>)}{!items.length&&<p className="muted">Todavía no hay archivos adjuntos.</p>}</div>;}
 const uploadControl=<label className={`upload-box ${busy?'disabled':''}`}><Upload size={24}/><strong>{busy?'Guardando…':isTeacher?'Adjuntar material de la tarea':'Subir mi solucionario'}</strong><span>PDF, JPG, PNG o WEBP · hasta 10 MB por archivo</span><span>Máximo 10 archivos · también puedes tomar fotos desde tu celular</span><input type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" aria-label={isTeacher?'Adjuntar material':'Subir solucionario'} disabled={busy||preview} onChange={e=>{upload(e.target.files);e.target.value='';}}/></label>;
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">f<span>·</span></span><div><strong>Fernando</strong><small>AULA PARTICULAR</small></div></div><div className="account"><span className="account-label">{preview?'Vista del alumno':data?.role==='student'?'Espacio del alumno':'Espacio del profesor'}</span><span className="avatar">{data?.role==='student'?'F':'P'}</span></div></header>
  <main className="workspace">
   {preview&&<div className="preview-bar"><Eye size={18}/><span>Vista previa de Fernando. No se envían respuestas desde esta vista.</span><Button variant="outline" onClick={()=>{setPreview(false);setActive(null);}}>Volver a profesor</Button></div>}
   {(error||notice)&&<div className={`message ${error?'error':'success'}`} role={error?'alert':'status'}>{error||notice}{!data&&<Button variant="outline" onClick={()=>run(async()=>{await reload();})}><RefreshCw size={16}/>Reintentar</Button>}</div>}
   {!data&&!error&&<div className="loading"><LoaderCircle className="spin"/>Cargando tu aula…</div>}
   {data?.role==='setup'&&<section className="setup-panel"><span className="eyebrow">TU AULA, LISTA PARA EMPEZAR</span><h1>Un espacio para<br/>aprender paso a paso.</h1><p>Crea las tareas de Fernando, recibe sus respuestas y revisa su desarrollo en un solo lugar.</p><div className="setup-items"><span><ClipboardCheck/>Preguntas con alternativas</span><span><Upload/>Solucionarios en PDF o fotos</span><span><CheckCircle2/>Notas y comentarios</span></div><Button size="lg" disabled={busy} onClick={()=>run(async()=>{await post({action:'setup'});await reload();},'Tu aula está activada. Crea la primera tarea.')}><GraduationCap/>Activar mi aula de profesor</Button><small>Se vinculará a tu cuenta: {data.email}</small></section>}
   {data&&data.role!=='setup'&&!active&&!editor&&<>
    <div className="page-heading"><div><p className="eyebrow">{isTeacher?'CLASES PARTICULARES':'TU ESPACIO DE APRENDIZAJE'}</p><h1>{isTeacher?'El aula de Fernando.':'Hola, Fernando.'}</h1><p>{isTeacher?'Prepara la próxima tarea y acompaña cada avance.':'Resuelve, marca tus respuestas y comparte tu desarrollo.'}</p></div>{isTeacher&&<Button size="lg" onClick={()=>{setEditor(blankTask());setError('');setNotice('');}}><Plus/>Nueva tarea</Button>}</div>
    <div className="stats"><div><span className="stat-icon blue"><BookOpen/></span><div><strong>{pending}</strong><span>Pendientes</span></div></div><div><span className="stat-icon amber"><Clock3/></span><div><strong>{pendingReview}</strong><span>Por revisar</span></div></div><div><span className="stat-icon green"><CheckCircle2/></span><div><strong>{completed}</strong><span>Revisadas</span></div></div></div>
    <Tabs value={tab} onValueChange={setTab}><div className="tabs-row"><TabsList variant="line"><TabsTrigger value="tasks">Tareas</TabsTrigger><TabsTrigger value="submissions">Entregas</TabsTrigger>{isTeacher&&<TabsTrigger value="access">Acceso</TabsTrigger>}</TabsList><div className="tabs-actions">{isTeacher&&<Button variant="ghost" onClick={()=>{setPreview(true);setTab('tasks');}}><Eye/>Ver como Fernando</Button>}<Button variant="ghost" size="icon" aria-label="Actualizar tareas" disabled={busy} onClick={()=>run(async()=>{await reload();})}><RefreshCw size={17}/></Button></div></div></Tabs>
    {tab==='access'&&isTeacher?<section className="panel access-panel"><LockKeyhole className="section-icon"/><h2>Acceso de Fernando</h2><p>Autoriza el correo con el que Fernando iniciará sesión en ChatGPT. Tu cuenta de profesor permanece separada.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await post({action:'student',email:studentEmail});await reload();},'Correo autorizado en el aula. Comprueba también el acceso compartido del sitio.');}}><label>Correo de Fernando<input type="email" value={studentEmail} onChange={e=>setStudentEmail(e.target.value)} placeholder="Correo del alumno" required/></label><Button disabled={busy} type="submit"><Save/>Guardar correo</Button></form><div className="note"><strong>Antes de compartir</strong><p>El sitio se entrega privado. Después de autorizar el correo, habilita el acceso para Fernando desde las opciones de compartir del sitio. Autorizar su correo aquí no cambia esa configuración.</p></div></section>:<div className="dashboard-grid"><section className="task-list"><div className="section-heading"><h2>{tab==='submissions'?'Entregas de Fernando':isTeacher?'Todas las tareas':'Mis tareas'}</h2><span>{visibleTasks.filter(t=>tab!=='submissions'||data.submissions.some(s=>s.task===t.id&&s.state!=='draft')).length} tareas</span></div>
    {!visibleTasks.filter(t=>tab!=='submissions'||data.submissions.some(s=>s.task===t.id&&s.state!=='draft')).length?<div className="empty"><div className="empty-icon"><BookOpen size={34}/></div><h2>{tab==='submissions'?'Las entregas aparecerán aquí':isTeacher?'La primera tarea empieza aquí':'Tu próxima tarea está en camino'}</h2><p>{tab==='submissions'?'Cuando Fernando envíe una tarea, podrás consultar sus respuestas y su solucionario.':isTeacher?'Escribe las preguntas, añade alternativas y decide cuándo publicarla.':'Tu profesor publicará aquí las actividades. Vuelve pronto para comenzar.'}</p>{isTeacher&&tab==='tasks'&&<Button onClick={()=>setEditor(blankTask())}><Plus/>Crear primera tarea</Button>}</div>:visibleTasks.filter(t=>tab!=='submissions'||data.submissions.some(s=>s.task===t.id&&s.state!=='draft')).map((t,i)=>{const s=data.submissions.find(s=>s.task===t.id);return <button className="task-card" key={t.id} onClick={()=>openTask(t)}><div className="task-index">{String(i+1).padStart(2,'0')}</div><div className="task-content"><div className="task-tags"><span className="subject">{t.subject}</span><span className={`badge ${s?.state||''}`}>{!t.published?'Borrador':stateLabel(s)}</span></div><h3>{t.title}</h3><div className="task-meta"><span>{t.questions.length} preguntas</span><span>Entrega: {formatDate(t.due)}</span></div></div>{s?.state==='reviewed'?<strong className="mini-score">{s.score}<small>/20</small></strong>:<ChevronRight className="task-arrow" size={21}/>}</button>;})}</section><aside className="study-note"><span className="eyebrow">UN PASO A LA VEZ</span><h2>El desarrollo<br/>también cuenta.</h2><p>Una respuesta muestra el resultado. Tu solucionario muestra cómo llegaste a él.</p><ol><li><span>1</span>Lee y resuelve las preguntas.</li><li><span>2</span>Marca tus alternativas.</li><li><span>3</span>Sube tu desarrollo y entrega.</li></ol><div className="note-footer"><GraduationCap size={21}/>Aprender es practicar.</div></aside></div>}
   </>}
   {editor&&<>
    <Button variant="ghost" onClick={()=>{setEditor(null);setError('');}}><ArrowLeft/>Cerrar editor</Button><div className="page-heading"><div><p className="eyebrow">ESPACIO DEL PROFESOR</p><h1>{editor.id?'Editar tarea':'Una nueva tarea.'}</h1><p>La clave correcta solo se mostrará al alumno cuando revises su entrega.</p></div></div>
    <div className="editor-layout"><div><section className="panel"><h2>Datos de la tarea</h2><label>Título<input value={editor.title} maxLength={160} onChange={e=>setEditor({...editor,title:e.target.value})} placeholder="Ej.: Ecuaciones de primer grado"/></label><div className="form-grid"><label>Curso<input value={editor.subject} maxLength={80} onChange={e=>setEditor({...editor,subject:e.target.value})} placeholder="Ej.: Matemática"/></label><label>Fecha de entrega · opcional<input type="date" value={editor.due} onChange={e=>setEditor({...editor,due:e.target.value})}/></label></div><label>Indicaciones<textarea rows={3} value={editor.instructions} maxLength={8000} onChange={e=>setEditor({...editor,instructions:e.target.value})}/></label></section>
    {editor.questions.map((q,i)=><section className="panel question-editor" key={q.id}><div className="section-heading"><h2>Pregunta {i+1}</h2><Button variant="ghost" size="icon" aria-label={`Quitar pregunta ${i+1}`} disabled={editor.questions.length===1} onClick={()=>setEditor({...editor,questions:editor.questions.filter((_,n)=>n!==i)})}><Trash2 size={17}/></Button></div><label>Enunciado<textarea rows={3} value={q.text} maxLength={4000} onChange={e=>editQuestion(i,{text:e.target.value})} placeholder="Escribe el problema. También puedes referirte a una pregunta del PDF adjunto."/></label><span className="field-label">Alternativas · marca la respuesta correcta</span><RadioGroup value={String(q.correct)} onValueChange={v=>editQuestion(i,{correct:Number(v)})} aria-label={`Clave de la pregunta ${i+1}`}>{q.options.map((o,j)=><div className={`option-edit ${q.correct===j?'correct':''}`} key={j}><RadioGroupItem value={String(j)} aria-label={`La alternativa ${letters[j]} es correcta`}/><span>{letters[j]}</span><input aria-label={`Alternativa ${letters[j]} de la pregunta ${i+1}`} value={o} maxLength={1000} onChange={e=>editQuestion(i,{options:q.options.map((v,k)=>k===j?e.target.value:v)})} placeholder={`Alternativa ${letters[j]}`}/>{q.correct===j&&<Check size={18}/>}</div>)}</RadioGroup><div className="option-tools"><Button variant="ghost" disabled={q.options.length<=2} onClick={()=>editQuestion(i,{options:q.options.slice(0,-1),correct:Math.min(q.correct||0,q.options.length-2)})}>Quitar alternativa</Button><Button variant="ghost" disabled={q.options.length>=5} onClick={()=>editQuestion(i,{options:[...q.options,'']})}>Añadir alternativa</Button></div></section>)}<Button variant="outline" size="lg" disabled={editor.questions.length>=60} onClick={()=>setEditor({...editor,questions:[...editor.questions,newQuestion()]})}><Plus/>Añadir pregunta</Button></div><aside className="panel editor-summary"><span className="eyebrow">ANTES DE PUBLICAR</span><h2>Todo listo para practicar.</h2><p>{editor.questions.length} pregunta{editor.questions.length===1?'':'s'} con alternativas.</p><p>Puedes guardar un borrador, adjuntar un PDF o fotos y publicarlo después.</p><Button disabled={busy} size="lg" onClick={()=>saveTask(true)}><Send/>{busy?'Guardando…':'Publicar tarea'}</Button><Button disabled={busy} variant="outline" size="lg" onClick={()=>saveTask(false)}><Save/>Guardar borrador</Button></aside></div>
   </>}
   {data&&task&&!editor&&<>
    <Button variant="ghost" disabled={busy} onClick={back}><ArrowLeft/>Volver a las tareas</Button><div className="page-heading"><div><div className="task-tags"><span className="subject">{task.subject}</span><span className={`badge ${sub?.state||''}`}>{!task.published?'Borrador':stateLabel(sub)}</span></div><h1>{task.title}</h1><p>{task.questions.length} preguntas · Entrega: {formatDate(task.due)}</p></div>{isTeacher&&!sub&&<Button variant="outline" onClick={()=>setEditor(JSON.parse(JSON.stringify(task)))}>Editar tarea</Button>}</div>
    {!task.published&&isTeacher&&<div className="note draft-note"><p>Este borrador todavía no es visible para Fernando. Añade tus archivos y publícalo cuando esté listo.</p><Button disabled={busy} onClick={()=>run(async()=>{await post({action:'saveTask',task:{...task,published:true}});await reload();},'Tarea publicada.')}><Send/>Publicar tarea</Button></div>}
    <div className="detail-layout"><div><section className="panel"><h2>Indicaciones</h2><p className="prewrap">{task.instructions||'Resuelve las preguntas y adjunta tu desarrollo.'}</p>{attachments('material',!!isTeacher)}{isTeacher&&!locked&&uploadControl}</section>
    {task.questions.map((q,i)=><section className="panel question-card" key={q.id}><p className="eyebrow">PREGUNTA {String(i+1).padStart(2,'0')}</p><h2 className="prewrap">{q.text}</h2><RadioGroup aria-label={`Respuesta de la pregunta ${i+1}`} value={answers[q.id]===undefined?'':String(answers[q.id])} disabled={!!isTeacher||preview||locked||busy} onValueChange={v=>{setAnswers({...answers,[q.id]:Number(v)});setDirty(true);}}>{q.options.map((o,j)=><label key={j} className={`answer-option ${answers[q.id]===j?'selected':''} ${sub?.state==='reviewed'&&q.correct===j?'right-answer':''}`}><RadioGroupItem value={String(j)}/><span className="option-letter">{letters[j]}</span><span className="prewrap">{o}</span>{sub?.state==='reviewed'&&q.correct===j&&<Check size={18}/>}</label>)}</RadioGroup>{isTeacher&&<p className="answer-key">Clave: {letters[q.correct??0]}{sub&&sub.answers[q.id]!==undefined?` · Fernando marcó ${letters[sub.answers[q.id]]}`:''}</p>}</section>)}
    <section className="panel"><h2>{isTeacher?'Solucionario de Fernando':'Mi solucionario'}</h2><p>Incluye tus operaciones, pasos y razonamiento. Revisa que las fotos se lean con claridad.</p>{attachments('solution',!isTeacher&&!preview)}{!isTeacher&&!locked&&!preview&&uploadControl}</section></div><aside className="detail-aside">
    {sub?.state==='reviewed'&&<section className="review-result"><span className="eyebrow">TAREA REVISADA</span><div className="grade">{sub.score}<span>/20</span></div><h3>Comentarios del profesor</h3><p className="prewrap">{sub.feedback}</p></section>}
    <section className="panel progress-panel"><h2>{isTeacher?'Revisión de la tarea':'Tu avance'}</h2><div className="progress-count"><strong>{Object.keys(answers).length}</strong><span>de {task.questions.length} respuestas</span></div><div className="progress-track"><span style={{width:`${Object.keys(answers).length/task.questions.length*100}%`}}/></div><div className="progress-check"><CheckCircle2 size={18}/>{data.files.filter(f=>f.task===active&&f.kind==='solution').length} archivos de desarrollo</div>
    {sub?.submitted&&<p className="muted">Entregado el {new Date(sub.submitted).toLocaleString('es-PE',{timeZone:'America/Lima'})}</p>}
    {isTeacher&&sub&&sub.state!=='draft'?<form onSubmit={e=>{e.preventDefault();run(async()=>{await post({action:'review',task:task.id,score:Number(score),feedback});await reload();},'Revisión guardada. Fernando ya podrá ver su nota y tus comentarios.');}}><label>Nota sobre 20<input type="number" min="0" max="20" step="0.1" value={score} onChange={e=>setScore(e.target.value)} required/></label><label>Comentarios<textarea rows={5} value={feedback} onChange={e=>setFeedback(e.target.value)} required placeholder="Explica qué hizo bien y qué debe mejorar."/></label><Button type="submit" disabled={busy}><ClipboardCheck/>Guardar revisión</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>run(async()=>{await post({action:'reopen',task:task.id});await reload();},'Entrega reabierta. Fernando puede corregir y volver a enviar.')}>Permitir nueva entrega</Button></form>:isTeacher?<p className="muted">La revisión se habilitará cuando Fernando entregue la tarea.</p>:preview?<p className="muted">Vista de consulta. Fernando podrá responder desde su cuenta.</p>:locked?<div className="submitted-note"><CheckCircle2/><strong>Tu tarea fue entregada.</strong><p>{sub?.state==='reviewed'?'Lee los comentarios de tu profesor.':'Tu profesor revisará tus respuestas y tu desarrollo.'}</p></div>:<><Button disabled={busy} size="lg" onClick={()=>run(async()=>{await post({action:'answers',task:task.id,answers,submit:true});setDirty(false);await reload();},'¡Tarea entregada! Tu profesor ya puede revisarla.')}><Send/>Entregar tarea</Button><Button variant="outline" disabled={busy} onClick={()=>run(async()=>{await post({action:'answers',task:task.id,answers,submit:false});setDirty(false);await reload();},'Respuestas guardadas. Puedes continuar después.')}><Save/>Guardar y continuar después</Button><small>{dirty?'Tienes respuestas sin guardar.':'Marca todas las preguntas y adjunta tu solucionario antes de entregar.'}</small></>}
    </section></aside></div>
   </>}
  </main><footer className="footer"><span>Fernando · Aula particular</span><span>Un espacio para aprender, practicar y avanzar.</span></footer>
 </div>;
}
