import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import ts from 'typescript';
const require=createRequire(import.meta.url);
const mfPath=require.resolve('miniflare',{paths:[require.resolve('wrangler/package.json')]});
const {Miniflare}=require(mfPath);
const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-05-15',d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false});
const out=path.resolve('.sites-runtime/test-modules');fs.mkdirSync(out,{recursive:true});
const compile=(source,target,replacements=[])=>{let s=fs.readFileSync(source,'utf8');for(const [a,b] of replacements)s=s.replaceAll(a,b);fs.writeFileSync(path.join(out,target),ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);};
let checks=0;
try{
 globalThis.testEnv={TEACHER_EMAIL:'teacher@example.test',DB:await mf.getD1Database('DB'),BUCKET:await mf.getR2Bucket('BUCKET')};
 fs.writeFileSync(path.join(out,'bindings.mjs'),'export const env=globalThis.testEnv; export const getChatGPTUser=async()=>globalThis.testUser;');
 compile('lib/classroom-server.ts','server.mjs',[["'cloudflare:workers'","'./bindings.mjs'"],["'@/app/chatgpt-auth'","'./bindings.mjs'"]]);
 compile('lib/task-schema.ts','task-schema.mjs');
 compile('lib/course-server.ts','course-server.mjs',[["'cloudflare:workers'","'./bindings.mjs'"],["'./classroom-server'","'./server.mjs'"],["'./task-schema'","'./task-schema.mjs'"]]);
 for(const name of ['classroom','files'])compile(`app/api/${name}/route.ts`,`${name}.mjs`,[["'@/lib/classroom-server'","'./server.mjs'"],["'@/lib/task-schema'","'./task-schema.mjs'"],["'@/lib/course-server'","'./course-server.mjs'"]]);
 for(const sql of fs.readFileSync('drizzle/0000_colossal_dexter_bennett.sql','utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await testEnv.DB.prepare(sql).run();
 const api=await import(pathToFileURL(path.join(out,'classroom.mjs')));const files=await import(pathToFileURL(path.join(out,'files.mjs')));
 const teacher={userId:'test-teacher',email:'teacher@example.test'},student={userId:'test-student',email:'student@example.test'};
 const setUser=u=>{globalThis.testUser=u;};
 const call=async(body,expected=200)=>{const r=await api.POST(new Request('https://class.test/api/classroom',{method:'POST',headers:{origin:'https://class.test','Content-Type':'application/json'},body:JSON.stringify(body)}));const j=await r.json();assert.equal(r.status,expected,JSON.stringify(j));checks++;return j;};
 const data=async()=>{const r=await api.GET();return {status:r.status,body:await r.json()};};
 setUser(null);assert.equal((await data()).status,401);checks++;
 setUser(student);assert.equal((await data()).status,403);checks++;setUser(teacher);assert.equal((await data()).body.role,'teacher');await call({action:'setup'});await call({action:'student',email:student.email});
 const task={title:'Prueba de ecuaciones',subject:'Matemática',instructions:'Desarrolla.',due:'2026-10-01',questions:[{id:'q1',text:'2x = 8',options:['2','4','8'],correct:1,solution:'Divide entre 2: x = 4.'}],published:true};
 const {id}=await call({action:'saveTask',task});const draft=await call({action:'saveTask',task:{...task,title:'No publicada',published:false}});
 setUser({userId:'intruder',email:'intruder@example.test'});assert.equal((await data()).status,403);checks++;
 setUser(student);let d=(await data()).body;assert.equal(d.tasks.length,1);assert.equal(d.tasks[0].questions[0].correct,undefined);assert.equal(d.tasks[0].questions[0].solution,undefined);checks++;assert.equal(d.role,'student');checks+=3;
 await call({action:'saveTask',task},403);await call({action:'review',task:id,score:20,feedback:'No'},403);
 await call({action:'answers',task:id,answers:{q1:3},submit:false},400);
 await call({action:'answers',task:id,answers:{q1:1},submit:false});assert.equal((await data()).body.submissions[0].answers.q1,1);checks++;
 await call({action:'answers',task:id,answers:{q1:1},submit:true},400);
 async function upload(name,bytes,expected=200){const f=new FormData();f.set('task',id);f.set('file',new File([bytes],name,{type:'application/pdf'}));const r=await files.POST(new Request('https://class.test/api/files',{method:'POST',headers:{origin:'https://class.test'},body:f}));const j=await r.json();assert.equal(r.status,expected,JSON.stringify(j));checks++;return j;}
 await upload('fake.pdf','<script>bad</script>',400);
 const attachment=await upload('desarrollo.pdf','%PDF-1.4\nTest solution');
 await call({action:'answers',task:id,answers:{q1:1},submit:true});
 await call({action:'answers',task:id,answers:{q1:0},submit:false},409);
 await upload('otro.pdf','%PDF-1.4\nOther',409);
 d=(await data()).body;assert.equal(d.tasks[0].questions[0].correct,undefined);checks++;
 setUser(teacher);d=(await data()).body;assert.equal(d.tasks.find(t=>t.id===id).questions[0].correct,1);assert.equal(d.files[0].name,'desarrollo.pdf');checks+=2;
 const download=await files.GET(new Request('https://class.test/api/files?id='+attachment.id));assert.equal(download.status,200);assert.match(await download.text(),/^%PDF/);checks+=2;
 await call({action:'saveTask',task:{...task,id}},409);
 await call({action:'review',task:id,score:21,feedback:'Bien'},400);
 await call({action:'review',task:id,score:20,feedback:'Buen desarrollo.'});
 setUser(student);d=(await data()).body;assert.equal(d.submissions[0].score,20);assert.equal(d.tasks[0].questions[0].correct,1);assert.equal(d.tasks[0].questions[0].solution,'Divide entre 2: x = 4.');checks+=3;
 setUser({userId:'intruder',email:'intruder@example.test'});assert.equal((await files.GET(new Request('https://class.test/api/files?id='+attachment.id))).status,403);checks++;
 setUser(teacher);await call({action:'reopen',task:id});
 setUser(student);d=(await data()).body;assert.equal(d.tasks[0].questions[0].correct,undefined);assert.equal(d.submissions[0].state,'draft');checks+=2;
 const csrf=await api.POST(new Request('https://class.test/api/classroom',{method:'POST',headers:{origin:'https://evil.test'},body:JSON.stringify({action:'answers',task:id,answers:{},submit:false})}));assert.equal(csrf.status,403);checks++;
 // Synthetic private curriculum tests do not publish the actual answer bank.
 const seedTasks=[1,2,3].map((n)=>({...task,id:crypto.randomUUID(),title:'Chapter task '+n,questions:[{...task.questions[0],id:'seed-q'+n}]}));
 testEnv.ALGEBRA_CH1_META=JSON.stringify({id:'test-chapter',title:'Test chapter',subject:'Test course',chapter:1,source:'Test source',convention:'Test convention',objectives:['Test objective'],taskIds:seedTasks.map(t=>t.id)});
 testEnv.ALGEBRA_CH1_TOPICS_A=JSON.stringify([{id:'topic',title:'Topic',pages:'Page 1',concept:'Concept',formulas:['Formula'],example:'Example',tip:'Tip'}]);
 testEnv.ALGEBRA_CH1_TOPICS_B='[]';
 seedTasks.forEach((t,i)=>testEnv['ALGEBRA_CH1_TASK_'+(i+1)]=JSON.stringify(t));
 setUser(teacher);d=(await data()).body;assert.equal(d.lesson.topics.length,1);assert.equal(d.tasks.length,5);checks+=2;
 d=(await data()).body;assert.equal(d.tasks.length,5);checks++;
 await call({action:'saveTask',task:{...seedTasks[0],title:'Teacher edit to preserve'}});
 d=(await data()).body;assert.equal(d.tasks.find(t=>t.id===seedTasks[0].id).title,'Teacher edit to preserve');checks++;
 setUser(student);d=(await data()).body;assert.equal(d.tasks.length,4);assert.ok(d.tasks.every(t=>t.questions.every(q=>q.correct===undefined&&q.solution===undefined)));assert.ok(!JSON.stringify(d.lesson).includes('Divide entre'));checks+=3;
 console.log(`PASS: ${checks} workflow, curriculum, persistence, file and authorization checks with local D1/R2.`);
}finally{await mf.dispose();}
